controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

register_page:
        path: /register
        controller: ../src/Controller/RegistrationController::index